### PR TITLE
Release v 0.5

### PR DESCRIPTION
**Pull request by IbimsnicesYolo**
Changelog:

- Complete File System Rework
- Cleaned Files, deleted unused Code + Files
- Reworked Config System
- Renamed Some Netmessages and Hooks
- Improved Blade Drawing
- Improved Performance at some Points
- Improved Networking
- Improved Hittracing Debugging
- Changed Hud Design (not final)
- Changed Force Power Bar Design
- Changed Close Button of Saber Crafter
- Fixed Sideblades/Quillon Positions
- Fixed Keybind Saving
- Fixed Saber Crafting not workin properly sometimes
- Fixed Saber Crafting Cam flying across the map
- Added a lot of Hooks for integrations
- Added Config Option to Block Damaging Other Players who are in the same Team
- Added an easy menu to give items to Players
- Added Informations for Force Power Cooldowns at the Force Power Bar
- Added Config Option to disable Build In ThirdPerson System
- Added Kylo Ren Hilt
- Saber Menu now opens instead of the Spawnmenu if your active weapon is a lightsaber
- Removed the Saber menu from Contextmenu
- Removed a lot of old Debug Stuff
- Removed Cheat Command for Items

And More I dont remember

Important Information!
This is just the first of multiple Big Updates! Please report errors to our Devs on the Discord Server

### CODE REVIEW

**Comment by IbimsnicesYolo** [comment]
Premium Changelog:

- Complete File System Rework
- Cleaned Files
- Config Rework
- Improved Drawing
- Improved Hitscanning
- Fixed Config for Combat Rolling
- Added Config Option to enable Hittracing of the Sideblades/Quillons
- Added Blade Effects and Animations
- Added Animated Crystal Examples
- Added Config Option to enable Animated Sideblades/Quillons
- Added Offhand Saber Crafting (didnt fixed every Bug yet)
- Added Example to create Lore Sabers / Pre Made Sabers

- Fixed Force Powers double existing
Important Information!
We are aware that some Force Powers dont work.
They will be fixed in the next update, also the remaining Offhand Bugs will be fixed then.

**Review by Nystoo — DISMISSED** [review]
do it

**Comment by Ov3rSimplified** [comment]
Do It!!!!

**Review by Ov3rSimplified — DISMISSED** [review]
Yes Commrade!

**Review by NetFl3xx — APPROVED** [review]
Approved

**Review by Nystoo — APPROVED** [review]
this time merge bitch

**Review by NetFl3xx — APPROVED** [review]
approve

**Review by Ov3rSimplified — APPROVED** [review]
Commrade!

**Pull request merged**
